### ISSUE TITLE
Courses URL

### ISSUE THREAD

**Issue by realZhangChi** [hikalkan/courses#1]
Hello, I am learning how to use the Abp framework to write programs, and I am trying to apply it to my project. 
I would be very grateful if you could provide me with your tutorial URL.

**Comment by hikalkan** [comment]
see https://github.com/abpframework/abp/issues/4668#issuecomment-668035505

Thanks :)

**Comment by charleszh-dev** [comment]
> see [abpframework/abp#4668 (comment)](https://github.com/abpframework/abp/issues/4668#issuecomment-668035505)
> 
> Thanks :)

Thank you 😊
